version: '3.9'

services:
  app:
    build:
      context: .
      target: dev
    container_name: maracuja-app
    working_dir: /app
    volumes:
      - ./:/app
      - rubygems:/usr/local/bundle
    ports:
      - "3000:3000"
    command: "ruby server.rb"

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: maracuja
      POSTGRES_PASSWORD: maracuja
      POSTGRES_DB: maracuja
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata

volumes:
  rubygems:
  pgdata:
