#!/bin/bash

docker rm -f sidekiq-web

docker run \
  -d \
  --rm \
  --name sidekiq-web \
  --network maracuja \
  -e REDIS_URL=redis://redis:6379/0 \
  -p "9292:9292" \
  maracuja \
  bash -c "rackup --port 9292 --host 0.0.0.0 sidekiq-web.ru"
